// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8AFodSA14eUfRdkX9DZhbObbcdmDCE40',
    appId: '1:740771744828:web:de5573a03c3e5f61390739',
    messagingSenderId: '740771744828',
    projectId: 'fir-services-a8bf0',
    authDomain: 'fir-services-a8bf0.firebaseapp.com',
    storageBucket: 'fir-services-a8bf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrbXCzQ9px8t0T2Vd7y5FWN1X93zsf9o',
    appId: '1:740771744828:android:6aef4e01e7a7085d390739',
    messagingSenderId: '740771744828',
    projectId: 'fir-services-a8bf0',
    storageBucket: 'fir-services-a8bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2S8PU_OzMhOm6YTw3INAqffzNjhJcCmc',
    appId: '1:740771744828:ios:c0501cfb84d61415390739',
    messagingSenderId: '740771744828',
    projectId: 'fir-services-a8bf0',
    storageBucket: 'fir-services-a8bf0.appspot.com',
    iosClientId: '740771744828-r22atcp6u68tga9531gqi7279ak5u0vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2S8PU_OzMhOm6YTw3INAqffzNjhJcCmc',
    appId: '1:740771744828:ios:c0501cfb84d61415390739',
    messagingSenderId: '740771744828',
    projectId: 'fir-services-a8bf0',
    storageBucket: 'fir-services-a8bf0.appspot.com',
    iosClientId: '740771744828-r22atcp6u68tga9531gqi7279ak5u0vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseServices',
  );
}
